Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,19 +42,15 @@ jobs:
        # Runs a set of commands using the runners shell
       - name: Build
         run: |
-
           WFID=$(curl -k -s -u fdadmin:fz#n1vTeHRNQy^9C -H "Content-Type: application/json" -d '{"environmentId":"'"$BUILDENVID"'", "streamId":"'"$STRMID"'"}' -X POST http://srvld20.noesis.pt/flexdeploy/rest/v1/project/$PRJID/build | jq '.workflowRequests[] | .workflowRequestId')
-
           CODE_BUILD=$(tail -n1 <<< "$WFID")
           echo "Workflow ID $WFID"
-
-
-           ST=$(echo $STATUS | tr -d '"')
-           if [[ "$ST" == "FAILED" ]]; then
-           echo "Build Failed."; exit 1 
-           elif [[ "$ST" == "COMPLETED" ]]; then
-           echo "Built."; exit 0
-           fi
-            sleep 10
+          ST=$(echo $STATUS | tr -d '"')
+          if [[ "$ST" == "FAILED" ]]; then
+            echo "Build Failed."; exit 1 
+          elif [[ "$ST" == "COMPLETED" ]]; then
+            echo "Built."; exit 0
+          fi
+          sleep 10
 
 
